### ISSUE TITLE
Failed to load a language-c package grammar

### ISSUE THREAD

**Issue by fanruizhe** [atom/language-c#329]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [language-c](https://github.com/atom/language-c) package 0.60.14

### Stack Trace

Failed to load a language-c package grammar

```
At The specified module could not be found.
\\?\C:\Users\admin\AppData\Local\atom\app-1.37.0\resources\app.asar.unpacked\node_modules\tree-sitter-c\build\Release\tree_sitter_c_binding.node in C:\Users\admin\AppData\Local\atom\app-1.37.0\resources\app.asar\node_modules\language-c\grammars\tree-sitter-c.json

Error: The specified module could not be found.
\\?\C:\Users\admin\AppData\Local\atom\app-1.37.0\resources\app.asar.unpacked\node_modules\tree-sitter-c\build\Release\tree_sitter_c_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146072)
    at /app.asar/node_modules/tree-sitter-c/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-c/index.js:11:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:688410)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:3461496)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:360367)
    at l.readFile (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:360208)
    at u (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:580079)
    at ~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:581332
    at ELECTRON_ASAR.js:530:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
  at /app.asar/node_modules/language-c/grammars/tree-sitter-c.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-file-icons 0.6.0 
atom-ide-ui 0.13.0 
atom-simplified-chinese-menu 0.6.5 
autocomplete-php 0.3.7 
busy-signal 2.0.1 
editor-background 1.2.42 
emmet 2.4.3 
file-icons 2.1.32 
goto 1.8.3 
ide-php 0.7.18 
intentions 1.1.5 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
monokai-php-css-syntax 0.2.2 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
php-integrator-autocomplete-plus 1.6.2 
remote-ftp 2.2.2 
simplified-chinese-menu 5.3.5 
sync-settings 0.8.6 
```

**Comment by rsese** [comment]
Thanks for the report - do you see this error just when starting Atom?  Also, did this start happening only recently, maybe after updating to 1.37.0?
